stages:
  - build
  - publish
  - deploy_to_aws

build-docker-image:
  stage: build
  tags:
    - aws
  script:
    - docker build -t $CI_REGISTRY_IMAGE:1.0 .

push-to-registry:
  stage: publish
  tags:
    - aws
  needs:
    - build-docker-image
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker push $CI_REGISTRY_IMAGE:1.0

deploy-docker-image:
  stage: deploy_to_aws
  needs:
    - push-to-registry
  before_script:
    - cat $AWS_PRIVATE_KEY > private_key.pem
    - chmod 400 private_key.pem
  script:
    - scp -i private_key.pem -o StrictHostKeyChecking=no ./docker-compose.yml $AWS_USER@$AWS_SERVER:/home/ec2-user/server
    - ssh -o StrictHostKeyChecking=no -i private_key.pem $AWS_USER@$AWS_SERVER "
      cd server;
      docker compose down &&
      docker compose up -d
      "
